<a href="https://colab.research.google.com/github/sebakrys/data-science-bootcamp-A-Z/blob/main/23_s7_metryki_regresja.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

In [3]:
y_true = 100 + 20 * np.random.randn(50)
y_true

array([110.22225682,  45.46416589, 105.86793986, 110.29351978,
        97.29075135,  85.86520156,  95.28134542,  93.71038016,
        91.24063033,  79.26124236, 145.58084306, 104.11574296,
       105.63462157, 112.85568175,  87.85995857, 109.27475403,
       112.80197471, 137.29290722, 108.24904085, 115.64430245,
        78.9091548 ,  98.36142392,  82.15248586,  92.94544408,
        86.91009776, 107.37700516,  77.19807834,  84.99951576,
        75.18044896,  68.95581244,  98.33393445,  69.89052466,
        99.64729032, 105.96032931, 113.60360478, 109.15821479,
       126.26476428,  98.66960536,  91.9906347 , 112.56565791,
        84.58542296,  81.23882959, 107.62357944,  81.00847295,
        87.75860561,  87.41847951, 106.60936967,  91.3054263 ,
       135.61477027, 102.43434362])

In [4]:
y_pred = y_true + 10 * np.random.randn(50)
y_pred

array([124.83138273,  44.35195865,  86.93881899, 119.38376494,
        99.98736066,  84.62203997,  83.38988277,  95.04751835,
        85.25995485,  92.57947971, 138.23153373, 108.57575344,
       113.42931323, 111.61124278, 101.63852466, 113.81606211,
       120.91031059, 124.96380417,  95.49983059, 120.44840034,
        78.9076178 ,  74.82603021,  99.85544325,  93.65054587,
        86.51330277, 112.81056646,  73.77785898,  64.80436879,
        88.92676689,  62.41404101,  92.38593133,  82.45519143,
       120.02659777, 104.98185917, 130.04323124,  99.64668699,
       121.16145579, 105.56535361, 104.89592242, 109.01892108,
        96.91372247,  75.51072078, 100.33021425,  90.34022825,
        95.01423378,  86.48074675, 105.08381768,  98.10098017,
       127.21064929, 125.20127003])

In [6]:
results = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
results.head()

       y_true      y_pred
0  110.222257  124.831383
1   45.464166   44.351959
2  105.867940   86.938819
3  110.293520  119.383765
4   97.290751   99.987361

In [7]:
results['error'] = results['y_true']-results['y_pred']
results.head()

       y_true      y_pred      error
0  110.222257  124.831383 -14.609126
1   45.464166   44.351959   1.112207
2  105.867940   86.938819  18.929121
3  110.293520  119.383765  -9.090245
4   97.290751   99.987361  -2.696609

In [16]:
def plot_regression_results(y_true, y_pred):
    results = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
    min = results[['y_true', 'y_pred']].min().min()
    max = results[['y_true', 'y_pred']].max().max()

    print(min, max)

    fig = go.Figure(data=[go.Scatter(x=results['y_true'], y=results['y_pred'], mode='markers'),
                    go.Scatter(x=[min, max], y=[min, max])],
                    layout=go.Layout(showlegend=False, width=800,
                                     xaxis_title='y_true',
                                     yaxis_title='y_pred',
                                     title='Regression results'))
    fig.show()
plot_regression_results(y_true, y_pred)

44.351958652076 145.58084305778175

In [21]:
y_true = 100 + 20 * np.random.randn(1000)
y_pred = y_true + 10 * np.random.randn(1000)
results = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
results['error'] = results['y_true'] - results['y_pred']

px.histogram(results, x='error', nbins=50, width=800)

# MEan Absolute Error -  Średni Błąd Bezwzględny

In [22]:
def mean_absolute_error(y_true, y_pred):
  return abs(y_true - y_pred).sum() / len(y_true)

mean_absolute_error(y_true, y_pred)

8.458859790695756

In [23]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_true, y_pred)

8.458859790695756

#Mean Squared Error - MSE - Błąd Sredniokwadratowy

In [24]:
def mean_squared_error(y_true, y_pred):
    return ((y_true - y_pred) ** 2).sum() / len(y_true)

mean_squared_error(y_true, y_pred)

109.5390856469789

In [25]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_true, y_pred)

109.5390856469789

#ROOT Mean Squared Error - MSE - Pierwiastek Błąd Sredniokwadratowy

In [26]:
def root_mean_squared_error(y_true, y_pred):
    return np.sqrt(((y_true - y_pred) ** 2).sum() / len(y_true))

root_mean_squared_error(y_true, y_pred)

10.466092186053919

In [27]:
np.sqrt(mean_squared_error(y_true, y_pred))

10.466092186053919

# Max Error - błąd maxymalny

In [28]:
def max_error(y_true, y_pred):
  return abs(y_true-y_pred).max()
max_error(y_true, y_pred)

37.27161183911946

In [29]:
from sklearn.metrics import max_error

max_error(y_true, y_pred)

37.27161183911946

# R2 Score - wsp. determinacji

In [30]:
def r2_score(y_true, y_pred):
    licznik = ((y_true - y_pred) ** 2).sum()
    mianownik = ((y_true - y_true.mean()) ** 2).sum()
    try:
        r2 = 1 - licznik  / mianownik
    except ZeroDivisionError:
        print('Dzielenie przez zero')
    return r2
r2_score(y_true, y_pred)

0.7234565588371469

In [31]:
from sklearn.metrics import r2_score

r2_score(y_true, y_pred)

0.7234565588371469